# Site settings
title: Lowkey
title_long: Lowkey | A blog by Matthew Wang
email: malsf21@gmail.com
description: > #
  Lowkey is a blog by Matthew Wang, a student, web developer, and video game player.
  Developed using Jekyll, Lowkey contains Matt's rambles, rants, projects, and random things
  that you may or may not find cool. Don't worry, he has nothing to Hyde!
baseurl: ""
url: "https://blog.matthewwang.me"
twitter_username: malsf21
github_username:  malsf21
repo: "http://github.com/malsf21/lowkey"

# Build settings
markdown: kramdown
exclude: [vendor]

# Paginate
gems: [jekyll-paginate]
paginate: 10

# Static Man! (I'm using this for comment sections)
staticman:
  allowedFields: ['name', 'email', 'comment']
  requiredFields: ['name', 'email', 'comment']
  commitMessage: "Here's the latest comment from Lowkey."
  branch: master
  path: _data/comments/{options.post-slug}
  filename: entry{@timestamp}
  format: 'yml'
  moderation: false
