# Site settings
title: Lowkey
title_long: Lowkey | A blog by Matthew Wang
email: malsf21@gmail.com
description: > #
  I'm Matt, and Lowkey is my blog. On Lowkey, I discuss random cool things, cool people, and cool ideas.
baseurl: ""
url: "https://blog.matthewwang.me"
twitter: malsf21
github:  malsf21
repo: "http://github.com/malsf21/lowkey"

# Build settings
markdown: kramdown
exclude: [vendor]

# Gem Configs
gems:
  - jekyll-paginate
  - jekyll-archives
paginate: 10

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive

# Static Man! (I'm using this for comment sections)
# staticman:
#   allowedFields: ['name', 'email', 'comment']
#   requiredFields: ['name', 'email', 'comment']
#   commitMessage: "Here's the latest comment from Lowkey."
#   branch: master
#   path: "_data/comments/{options.slug}"
#   filename: entry{@timestamp}
#   format: 'yml'
#   moderation: true
