---
title: Lowkey
timezone: UTC
collections:
  category:
    output: true
  posts:
    title: Posts
    output: true
  specials:
    title: Specials
    output: true
  stats:
    title: Stats
    output: true
specials_list:
  - "hindsight2018"
  - "15at15"
  - "shad2016"
title_long: Lowkey | A blog by Matthew Wang
email: matt@matthewwang.me
author:
  name: Matthew Wang
  twitter: malsf21
description: "I'm Matt, and Lowkey is my blog. On Lowkey, I discuss random cool things,
  cool people, and cool ideas.

"
baseurl: ''
url: https://blog.matthewwang.me
twitter:
  username: malsf21
github: malsf21
repo: http://github.com/malsf21/lowkey
website: https://matthewwang.me
logo: "/img/lowkey-simple.png"
markdown: kramdown
exclude:
  - vendor
  - LICENSE.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - .sass-cache
  - .git
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 10
